#!/usr/bin/env bash
# create user dani as sudoer with temporary password
useradd -m -s $(which fish) -G sudo dani
echo "dani:replace_me!" | chpasswd

# copy root ssh public key to dani
mkdir -p /home/dani/.ssh
cp /root/.ssh/authorized_keys /home/dani/.ssh/authorized_keys
chown -R dani:dani /home/dani/.ssh
chmod 700 /home/dani/.ssh
chmod 600 /home/dani/.ssh/authorized_keys

# disable all login methods for root (password and ssh key)
rm /root/.ssh/authorized_keys
passwd -l root

# ssh: disable root access, enforce ssh key login globally (no password)
mkdir -p /etc/ssh
cat >> /etc/ssh/sshd_config << EOF
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
KbdInteractiveAuthentication no
EOF

# silence login messages for root and dani
touch /root/.hushlogin
touch /home/dani/.hushlogin
chown dani:dani /home/dani/.hushlogin

# set fish as default shell for root and dani
chsh -s $(which fish)
chsh -s $(which fish) dani

# install and set up starship for root and dani in fish and bash
curl -sS https://starship.rs/install.sh | sh -s -- -y
echo 'starship init fish | source' >> /root/.config/fish/config.fish
echo 'eval "$(starship init bash)"' >> /root/.bashrc
mkdir -p /home/dani/.config/fish
echo 'starship init fish | source' >> /home/dani/.config/fish/config.fish
echo 'eval "$(starship init bash)"' >> /home/dani/.bashrc

# add ll alias for fish and bash for root and dani
echo "alias ll='ls -alh --color=auto'" >> /root/.config/fish/config.fish
echo "alias ll='ls -alh --color=auto'" >> /root/.bashrc
echo "alias ll='ls -alh --color=auto'" >> /home/dani/.config/fish/config.fish
echo "alias ll='ls -alh --color=auto'" >> /home/dani/.bashrc

# set default editor to vim for root and dani
echo 'set -gx EDITOR vim' >> /root/.config/fish/config.fish
echo 'set -gx VISUAL vim' >> /root/.config/fish/config.fish
echo 'export EDITOR=vim' >> /root/.bashrc
echo 'export VISUAL=vim' >> /root/.bashrc
echo 'set -gx EDITOR vim' >> /home/dani/.config/fish/config.fish
echo 'set -gx VISUAL vim' >> /home/dani/.config/fish/config.fish
echo 'export EDITOR=vim' >> /home/dani/.bashrc
echo 'export VISUAL=vim' >> /home/dani/.bashrc

# TODO
# - set up nginx
# - set up certbot + nginx
# - set up reverse proxies
# - set up ufw rules
# - set up backups
# - set up docker-compose n stuff with automatic container updates, config updates, etc
# ^ webhook + git for this?
# - set up ddns
# - set up vpn/wireguard?

